In [ ]:
#sort in list
a = [8,23,5,12,67,9]
a.sort()
print(a)

[5, 8, 9, 12, 23, 67]


In [ ]:
#sorted in list
a = [8,23,5,12,67,9]
b = sorted(a)
print(b)

[5, 8, 9, 12, 23, 67]


In [ ]:
#sorted in tuple
a = (8,23,5,12,67,9)
b = sorted(a)
print(a)
print(b)


(8, 23, 5, 12, 67, 9)
[5, 8, 9, 12, 23, 67]


In [ ]:
import numpy as np

In [ ]:
#reshape np.arange
A = np.arange(1,13).reshape(3,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#reshape np.linspace
A = np.linspace(1,13,12).reshape(3,4)
print(A )

[[ 1.          2.09090909  3.18181818  4.27272727]
 [ 5.36363636  6.45454545  7.54545455  8.63636364]
 [ 9.72727273 10.81818182 11.90909091 13.        ]]


In [ ]:
#reshape np.array
A = np.array([23,45,12,5,134,57,45,87]).reshape(2,2,2)    #reshaping while creating array
print(A)

[[[ 23  45]
  [ 12   5]]

 [[134  57]
  [ 45  87]]]


In [ ]:
#reshape RESIZE                              reshape - changes needs saving in another variable
A = np.array([23,45,12,5,134,57,45,87])
A.resize(2,2,2)                #changes the shape of original array
print(A)

[[[ 23  45]
  [ 12   5]]

 [[134  57]
  [ 45  87]]]


In [ ]:
A = np.array([35,56,78,90])
B = np.array([7,9,3,12])         #list will thow an error while arrays iterate themselves
c = A-B
d = A+B
print(c)
print(d)

[28 47 75 78]
[ 42  65  81 102]


In [ ]:
A = np.array([35,56,78,90])
B = np.array([34.5,56.7,78.9,90,1])
#C = np.array(["234","45","67"])            strings in array cant be min or max same in lists also
print(A.max())
print(A.min())
print(B.max())
print(B.min())
#print(C.max())            error
#print(C.min())              error

90
35
90.0
1.0


In [ ]:
A = np.array([35,56,78,90]).reshape(2,2)
B = np.array([7,9,3,12]) .reshape(2,2)
print(A)
print("____________________")
print(B)
print("____________________")
C = A*B                                #one on one mul in matrix
print(C)

[[35 56]
 [78 90]]
____________________
[[ 7  9]
 [ 3 12]]
____________________
[[ 245  504]
 [ 234 1080]]


In [ ]:
A = np.array([35,56,78,90]).reshape(2,2)
B = np.array([7,9,3,12]) .reshape(2,2)
print(A)
print("____________________")
print(B)
print("____________________")
C = A@B
D = A.dot(B)                      #Matrix multiplication
print(C)
print("____________________")
print(D)

[[35 56]
 [78 90]]
____________________
[[ 7  9]
 [ 3 12]]
____________________
[[ 413  987]
 [ 816 1782]]
____________________
[[ 413  987]
 [ 816 1782]]


In [ ]:
#min max of every rows and columns in array
A = np.array([35,56,78,90,632,869,12,8,221,45,27,123,75,987,34,20]).reshape(4,4)
print(A)
print("____________________")
print("max in col",A.max(axis=0))             #axis=0 i.e.,column
print("____________________")
print("max in row",A.max(axis=1))             #axis=1 i.e.,row
print("____________________")
print("min in col",A.min(axis=0))
print("____________________")
print("min in row",A.min(axis=1))

[[ 35  56  78  90]
 [632 869  12   8]
 [221  45  27 123]
 [ 75 987  34  20]]
____________________
max in col [632 987  78 123]
____________________
max in row [ 90 869 221 987]
____________________
min in col [35 45 12  8]
____________________
min in row [35  8 27 20]


In [ ]:
#joining arrays  in vertically stacking                      vstac --- axis=0
A = np.array([35,56,78,90]).reshape(2,2)
B = np.array([7,9,3,12]) .reshape(2,2)
print(A)
print("__________________________")
print(B)
print("After vertically stacking two arrays")
print(np.vstack((A,B)))                                 #if (B,A) then B matrix will be on top

[[35 56]
 [78 90]]
__________________________
[[ 7  9]
 [ 3 12]]
After vertically stacking two arrays
[[35 56]
 [78 90]
 [ 7  9]
 [ 3 12]]


In [ ]:
#joining 2 matrix horizontally stacking                      hstack --- axis=1
A = np.array([35,56,78,90]).reshape(2,2)
B = np.array([7,9,3,12]) .reshape(2,2)
print(A)
print("__________________________")
print(B)
print("After horizontally stacking two arrays")
print(np.hstack((A,B)))                                 #if (B,A) then B matrix will be on front

[[35 56]
 [78 90]]
__________________________
[[ 7  9]
 [ 3 12]]
After horizontally stacking two arrays
[[35 56  7  9]
 [78 90  3 12]]


In [ ]:
 #dstack                                                according to dimension
A=np.arange(30).reshape(2,3,5)
print(A)
print("After dstack")
print(np.dstack(A)) #no.of rows --->  no.of groups
#no.of columns in every group --->  no.of rows in every group


[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
After dstack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
#Splitten array
A=np.arange(18).reshape(6,3)
print(A)
print("After splitting vertically")
np.vsplit(A,3)                          #(A,num) num = no.of matrices we are going to split

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting vertically


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [ ]:
#Splitten array in our way
A=np.arange(18).reshape(6,3)
print(A)
print("After splitting vertically")
np.vsplit(A,(2,3,5)  )

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting vertically


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[ 9, 10, 11],
        [12, 13, 14]]),
 array([[15, 16, 17]])]

In [ ]:
#splitting horizontally array
A=np.arange(18).reshape(3,6)
print(A)
print("After splitting horizontally")
np.hsplit(A,3)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
After splitting horizontally


[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17]])]

In [ ]:
#splitting horizontally array in our choice
A=np.arange(18).reshape(3,6)
print(A)
print("After splitting horizontally")
np.hsplit(A,(2,5))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
After splitting horizontally


[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3,  4],
        [ 8,  9, 10],
        [14, 15, 16]]),
 array([[ 5],
        [11],
        [17]])]

In [ ]:
#argmax in column ||  a.argmax()  if max in whole array             argmax is frequently used in pixels
A = np.array([17,4,18,56,12,33,89,21,34,55,11,13]).reshape(3,4)                #[0 0 0]
print(A)                                                                       #[1 1 1]
print(A.argmax(axis = 0))                                                      #[2 2 2]

[[17  4 18 56]
 [12 33 89 21]
 [34 55 11 13]]
[2 2 1 0]


In [ ]:
#argmax of rows in array
A = np.array([17,4,18,56,12,33,89,21,34,55,11,13]).reshape(3,4)             #[[0 1 2]
print(A)                                                                    # [0 1 2]
print(A.argmax(axis = 1))                                                   # [0 1 2]]

[[17  4 18 56]
 [12 33 89 21]
 [34 55 11 13]]
[3 2 1]


In [ ]:
#argmin of rows,columns in arrays
A = np.array([17,4,18,56,12,33,89,21,34,55,11,13]).reshape(3,4)
print(A)
print("columns",A.argmin(axis = 0))
print("_______________")
print("rows",A.argmin(axis = 1))



[[17  4 18 56]
 [12 33 89 21]
 [34 55 11 13]]
columns [1 0 2 2]
_______________
rows [1 0 2]


STATISTICS

In [ ]:
#mean , median, std ,var  --formulas should be in document
A = np.array([12,34,25,66,71,88])
print("Mean :",np.mean(A))
print("Median : ",np.median(A))
print("Variance : ",np.var(A))
print("Standard Deviation : ",np.std(A))

Mean : 49.333333333333336
Median :  50.0
Variance :  743.888888888889
Standard Deviation :  27.274326552435515


TRIGONOMETRY

In [ ]:
A = np.pi                #pi = 180
print(A)                #radians

3.141592653589793


In [ ]:
np.rad2deg(A)

180.0

In [ ]:
B = np.array([np.pi/4, np.pi/3, np.pi/2, np.pi/1])
print(B)

[0.78539816 1.04719755 1.57079633 3.14159265]


In [ ]:
print(np.rad2deg(B))

[ 45.  60.  90. 180.]


In [ ]:
c = np.array([0,30,45,60,90,120,180])
d = np.deg2rad(c)
print(d)

[0.         0.52359878 0.78539816 1.04719755 1.57079633 2.0943951
 3.14159265]


In [ ]:
np.sin(c)

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666,
        0.58061118, -0.80115264])

In [ ]:
np.cos(c)

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362,
        0.81418097, -0.59846007])

In [ ]:
np.sec(c)

AttributeError: module 'numpy' has no attribute 'sec'

In [ ]:
np.tan(c)

array([ 0.        , -6.4053312 ,  1.61977519,  0.32004039, -1.99520041,
        0.71312301,  1.33869021])

In [ ]:
np.arcsin(1)   #sin^-1

1.5707963267948966

In [ ]:
np.arccos(1)    #cos^-1

0.0

In [ ]:
np.arctan(1)      #tan^-1

0.7853981633974483

In [ ]:

a = 6
b = 4
print(np.hypot(a,b))                 #hypotenuse

7.211102550927978


SEARCHING

In [ ]:
A = np.array([90,3,45,21,34,90,21])
print(np.where(A==21))

(array([3, 6]),)


In [ ]:
A = np.array([90,3,45,21,34,90,21])
print(np.where(A%2==0))     #even

(array([0, 4, 5]),)


In [ ]:
A = np.array([90,3,45,21,34,90,21])
print(np.where(A>25 ))

(array([0, 2, 4, 5]),)


In [ ]:
A = np.array([90,3,45,22,34,80,21])
print(np.searchsorted(A,45))      #it gives index position as output after performing sorting   #outputs the index of a sorted element
#3,21,22,34,45,80,90

5


LINEAR ALGEBRA AND UNIVERSAL FUNCTION

In [ ]:
A = np.array([6,24,60,12,18])
B = np.array([6,4,10,5,4])
print(np.add(A,B))
print(np.subtract(A,B))
print(np.divide(A,B))
print(np.mod(A,B))
print(np.divmod(A,B))

[12 28 70 17 22]
[ 0 20 50  7 14]
[1.  6.  6.  2.4 4.5]
[0 0 0 2 2]
(array([1, 6, 6, 2, 4]), array([0, 0, 0, 2, 2]))


In [ ]:
A = np.array([6,12,34,56,9,10])
print(np.diff(A))

[  6  22  22 -47   1]


SET FUNCTIONS

In [ ]:
A = np.array([6,24,60,12,18])
B = np.array([6,4,10,5,4])
print(np.union1d(A,B))
print(np.setdiff1d(A,B))
print(np.intersect1d(A,B))

[ 4  5  6 10 12 18 24 60]
[12 18 24 60]
[6]


ROUNDING!

In [ ]:
a1 = np.trunc([-3.166,3.166])
print(a1)

[-3.  3.]


In [ ]:
a1 = np.fix([-3.166,3.166])
print(a1)

[-3.  3.]


In [ ]:
a1 = np.floor([-3.166,3.166])
print(a1)

[-4.  3.]


In [ ]:
a1 = np.ceil([-3.166,3.166])
print(a1)

[-3.  4.]


In [ ]:
a1 = np.around([-3.166,3.166])
print(a1)


[-3.  3.]


In [ ]:
A = np.array([6,24,60,12,18])
print(np.trunc(A))
print(np.fix(A))
print(np.around(A))
print(np.ceil(A))
print(np.floor(A))

[ 6. 24. 60. 12. 18.]
[ 6. 24. 60. 12. 18.]
[ 6 24 60 12 18]
[ 6. 24. 60. 12. 18.]
[ 6. 24. 60. 12. 18.]


In [ ]:
A = np.array([6,24,60,12,18])
print(np.cumsum(A))

[  6  30  90 102 120]


In [ ]:
A = np.array([6,24,60,12,18])
print(np.cumprod(A))

[      6     144    8640  103680 1866240]


In [ ]:
print(np.lcm(34,56))
print(np.gcd(445,655))

952
5


In [ ]:
Ar = np.array([45,65,30])
print(np.lcm.reduce(Ar))

1170


In [ ]:
Ar = np.array([45,65,30])
print(np.gcd.reduce(Ar))

5


In [ ]:
#subpackage    linear algebra
A = np.array([[1,2],[3,4]])
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


Random subpackage in numpy

In [ ]:
from numpy import random as rd

In [ ]:
A = rd.rand()   #default limit to 0 to 0.99
print(A)
A1 = rd.rand(10)
print(A1)

0.601964777729809
[0.55313385 0.22327446 0.16368051 0.01530122 0.78728694 0.63879653
 0.63842912 0.13339956 0.06491985 0.10561039]


In [ ]:
#randint
A = rd.randint(4)                   #limit --->0,1,2,3
print(A)

0


In [ ]:
A = rd.randint(50,size=6)                          #limit 0-49  and size any random elements
print(A)
A = rd.randint(50,size=(2,3))
print(A)

[26  5 10 17 21 32]
[[ 8 44 36]
 [32 18 23]]


Joins!

In [ ]:
A = np.array([1,2,3])
B = np.array([4,5,6])
#1x4 + 2x5 + 3x6
print(np.inner(A,B))

32


In [ ]:
A = np.array([1,2,3])
B = np.array([4,5,6])
#1x(4,5,6)  2x(4,5,6)  3x(4,5,6)
print(np.outer(A,B))

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [ ]:
A = np.array([1,2,3])
B = np.array([4,5,6])
#[(1x5)-(4x2) (1x6)-(3x4)]    determinant
print(np.cross(A,B))

[-3  6 -3]
