In [ ]:
#variable
a = 10
print("I am ",a,"years old")

I am  10 years old


In [ ]:
#arthmetic on int variables
a=int(input("Enter a value: "));
b=int(input("Enter b value: "))
print("SUM: ",a+b)
print("DIFF: ",a-b)
print("PROD: ",a*b)
print("Quotient: ",a/b)
print("Reminder: ",a%b)
print("Power of ",a," to",b," is: ",a**b)
print("Floor: ",a//b)

Enter a value: 12
Enter b value: 6
SUM:  18
DIFF:  6
PROD:  72
Quotient:  2.0
Reminder:  0
Power of  12  to 6  is:  2985984
Floor:  2


In [ ]:
#Take a number from the user which is a salary,If the salary is more then 50000 there is a 10% tax print his final salary.
a=int(input("Enter Salary"))
if(a>=50000):
  print("The salary after deducting tax: ",a-(a*(10/100)))
else:
  print("Your salary is less than 50000 So no tax deduction")

Enter Salary50000
The salary after deducting tax:  45000.0


In [3]:
#Get the salary from the user,if the salary is more than or equal to 50k apply 10% tax deduction ,if the salary is less than 50k apply 5% tax, if the salary is more than 70k apply 12% tax, if your salary exceeds 1L print Your promoted to next level
sal=int(input("Enter Salary: "))
if(sal<=50000):
  print("The salary after deducting tax 5%: ",sal-(sal*(5/100)))
elif(sal<=70000):
  print("The salary after deducting tax 10%: ",sal-(sal*(10/100)))
elif(sal<=100000):
  print("The salary after deducting tax 12%: ",sal-(sal*(12/100)))
else:
  print("You are Promoted")

Enter Salary: 101200
You are Promoted


In [ ]:
#range with for
#a= range(1,6)
n=int(input("Enter num: "))
for i in range(1,13):
   print(n, "*" ,i, "=", n*i)


Enter num: 67
67 * 1 = 67
67 * 2 = 134
67 * 3 = 201
67 * 4 = 268
67 * 5 = 335
67 * 6 = 402
67 * 7 = 469
67 * 8 = 536
67 * 9 = 603
67 * 10 = 670
67 * 11 = 737
67 * 12 = 804
range(1, 6)


In [ ]:
#while without range
n=int(input("Enter num: "))
i=1
while(i<=12):
  print(n, "*" ,i, "=", n*i)
  i+=1


Enter num: 57
57 * 1 = 57
57 * 2 = 114
57 * 3 = 171
57 * 4 = 228
57 * 5 = 285
57 * 6 = 342
57 * 7 = 399
57 * 8 = 456
57 * 9 = 513
57 * 10 = 570
57 * 11 = 627
57 * 12 = 684


In [ ]:
#List:Heterogeneous
L1=[1,"Kill",89,"chat",8.1,True]
for i in L1:
  print(i)

1
Kill
89
chat
8.1
True


In [ ]:
#append
L1=[1,"Kill",89,"chat",8.1]
L1.append(67)
print(L1)

[1, 'Kill', 89, 'chat', 8.1, 67]


In [ ]:
#insert
L1=[1,"Kill",89,"chat",8.1,True]                    #syntax: listname.insert(/index)
L1.insert(4,"Yeah")
print(L1)

[1, 'Kill', 89, 'chat', 'Yeah', 8.1, True]


Logical operators:

and - both conditions true : o/p-true

In [ ]:
#appendind 2 lists
L2=["Poppy","Bobby"]                   #syntax:  list1.extend(list2)
L1.extend(L2)   #L1+L2
print(L1)

[1, 'Kill', 89, 'chat', 8.1, True, 'Poppy', 'Bobby']


In [ ]:
#pop
L1=[1, 'Kill', 89, 'chat', 8.1, True, 'Poppy', 'Bobby']
L1.pop()
print(L1)                             #syntax: listname.pop(  )     or   listname.pop(//index number)
L1.pop(3)
print(L1)

[1, 'Kill', 89, 'chat', 8.1, True, 'Poppy']
[1, 'Kill', 89, 8.1, True, 'Poppy']


In [ ]:
#remove
L1=[1, 'Kill', 89, 'chat', 8.1, True, 'Poppy', 'Bobby']
                                #syntax: listname.remove(//element in list)
print(L1)
L1.remove("chat")
print(L1)

[1, 'Kill', 89, 'chat', 8.1, True, 'Poppy', 'Bobby']
[1, 'Kill', 89, 8.1, True, 'Poppy', 'Bobby']


In [ ]:
#clear
L1=[1, 'Kill', 89, 'chat', 8.1, True, 'Poppy', 'Bobby']
L1.clear()
print(L1)

[]


In [ ]:
#delete
L1=[1, 'Kill', 89, 'chat', 8.1, True, 'Poppy', 'Bobby']
del(L1)
#error:print(L1)

In [ ]:
#Create a list of 10 integer elements print their squares save these squares in a new list
L1=[1,2,3,4,5,6,7,8,9,10]
l2=[]
for x in L1:
  x=x*x                          #l2.append(x*x)
  l2.append(x)
print(l2)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [ ]:
#list comprehenssions
#newlist = [output for]
L1=[1,2,3,4,5,6,7,8,9,10]
L2=[x*x for x in L1]
print(L2)


[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [ ]:
#for and if in LC
L1=[1,2,3,4,5,6,7,8,9,10]
L2=[x*x for x in L1 if x>3]
print(L2)


[16, 25, 36, 49, 64, 81, 100]


In [ ]:
# for and if-else in lc
#newlist = [(stmt of if) if (cond) else (stmt of else) for]
L1=[23,67,12,34,69]
L2=[x*x if x>50 else 'X' for x in L1 ]
print(L2)

['X', 4489, 'X', 'X', 4761]


In [ ]:
#Take the salary from the user if salary is less than 50k 10% tax otherwise 15% tax
n=int(input("Enter Salary: "))
L1=[n]
#L1.append(n)
L2=[i-(i*0.1) if i<50000 else i-(i*0.15) for i in L1]
print(L2)

Enter Salary: 14000
[0.9]


In [ ]:
#taking salaries in list
L1=[78000,50400,34000,23000,14000]
L2=[i-(i*0.1) if i<50000 else i-(i*0.15) for i in L1]
print(L2)

[66300.0, 42840.0, 30600.0, 20700.0, 12600.0]


In [ ]:
#Dictionary
#dictname={key1:val1,key2:val2,......}
dict1={"Mentor":'Jwalitha',34:'Likitha',36:'Ramya',36:'Lavanya'}
print(dict1)

{'Mentor': 'Jwalitha', 34: 'Likitha', 36: 'Lavanya'}


In [1]:
#nested dictionary
dict2={"dept":"cse","details":{'year':'II','sec':'D','count':71}}
print(dict2["details"]['sec'])


D


In [2]:
#nested dictionary
dict2={"dept":"cse","details":{'year':'II','sec':'D','count':71}}
print("year is",dict2["details"]["year"])
print("secton is",dict2["details"]["sec"])
print("strength is",dict2["details"]["count"])


year is II
secton is D
strength is 71


In [3]:
#create dictionary using 2 lists
id=[34,55,12,35,12]
names=["joe","suchi","rohini","shankar","mani"]
nz=dict((zip(names,id)))
print(nz)


{'joe': 34, 'suchi': 55, 'rohini': 12, 'shankar': 35, 'mani': 12}


**NUMPY**

In [1]:
#create a 1d array
import numpy as np
a=np.array([1,2,3,4])        #1d array
print(a.ndim)
print(a.shape)


1
(4,)


In [3]:
#create a 2 dim array
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[15,66,77,88]])
#element in each row=coloumn                              #2d array
print(a.ndim)
print(a.shape)
print(a)

2
(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [15 66 77 88]]


In [4]:
#create a 3d array
import numpy as np
a=np.array([[[1,2,3,4],[5,6,7,8],[15,66,77,88]],[[1,2,9,8],[1,3,4,3],[5,6,5,9]]])
#element in each row=coloumn                              #3d array
print(a.ndim)
print(a.shape)
print(a)


3
(2, 3, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [15 66 77 88]]

 [[ 1  2  9  8]
  [ 1  3  4  3]
  [ 5  6  5  9]]]


In [5]:
#ones() function use
a=np.ones((4,2,3))              #groups,rows,col
print(a)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [6]:
#identity matrix  eye fun
a=np.eye(4,4)
print(a)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
a=np.arange(1,10,3)         #start,stop,step
print(a)
print(type(a))


[1 4 7]
<class 'numpy.ndarray'>


In [8]:
#print all the numbers that are divisiable by 8 by range function between 1 to 1000
a=np.arange(8,1001,8)
print(a)
print(type(a))


[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]
<class 'numpy.ndarray'>


In [9]:
#spilting a range into n numbers with common diffrence
a=np.linspace(31,12,8)
print(a)


[31.         28.28571429 25.57142857 22.85714286 20.14285714 17.42857143
 14.71428571 12.        ]
